### ISSUE TITLE
doScanner时找不到类

### ISSUE THREAD

**Issue by liwuyong** [qq53182347/liughMVC#1]
MyDispatcherServlet.java  doScanner方法 157行
URL url  =this.getClass().getClassLoader().getResource("/"+packageName.replaceAll("\\.", "/"));
idea在本地内嵌jetty运行时，url为空指针错误。将   "/"+packageName.replaceAll("\\.", "/")  改为 packageName.replaceAll("\\.", "/")时才可以取到url，不知道博主有这个问题吗？

**Comment by qq53182347** [comment]
有遇到,idea里tomcat也会报空指针.eclipse里就好着
